name: "Build and Deploy"

on: [push]

env:
  AZURE_WEBAPP_NAME: chrisblog-linuxapp # set this to your app name
  AZURE_WEBAPP_PACKAGE_PATH: './published'
  NETCORE_VERSION: '3.1.103'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2

    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restore
      run: dotnet Restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: 'Publish app for deploy'
      run: donet publish --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} 

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH}}

